name: "jaffle_shop"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# -------------------------------
# RUN LEVEL HOOKS
# -------------------------------
on-run-start:
  - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('run_start')"

on-run-end:
  - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('run_end')"

# -------------------------------
# MODEL CONFIGURATION
# -------------------------------
models:
  jaffle_shop:

    # -------- STAGING --------
    stagging:
      +materialized: view 
      +pre-hook:
        - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('stagging_model_start')"
      +post-hook:
        - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('stagging_model_end')"

    # -------- EXAMPLE --------
    example:
      +materialized: table
      +pre-hook:
        - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('example_model_start')"
      +post-hook:
        - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('example_model_end')"

    # -------- MARTS --------
    marts:
      +materialized: table
      +tags : ["High"]
      +pre-hook:
        - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('marts_model_start')"
      +post-hook:
        - "insert into RAW.JAFFLE_SHOP.DBT_AUDITS (audit_type) values ('marts_model_end')"

flags:
  require_generic_test_arguments_property: true
